Added models, with incomplete setup ActiveAdmin
EugeneTymoshenko/margatsni pull request #3
Opened 2019-02-25 16:03 UTC by hawkprovvv

In ActiveAdmine not can complete setup with Sorcery yet...

2019-02-26 09:02 UTC, slenderock requested changes

2019-02-26 09:02 UTC, slenderock commented on config/locales/devise.en.yml
> +# Additional translations at https://github.com/plataformatec/devise/wiki/I18n
delete this file

2019-02-26 09:02 UTC, slenderock commented on db/schema.rb
> +  create_table "active_admin_comments", force: :cascade do |t|
thus changes shouldn't be here

2019-02-26 09:02 UTC, slenderock commented on test/models/admin_user_test.rb
> +require 'test_helper'
remove!

2019-02-26 09:02 UTC, slenderock commented on test/fixtures/admin_users.yml
> +# Read about fixtures at http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
remove!

2019-02-26 09:02 UTC, slenderock commented on config/environments/development.rb
> +  #config.action_mailer.default_url_options = { :host => 'localhost:3000' }
remove this line

2019-02-26 09:02 UTC, slenderock commented on app/models/post.rb
> +  belongs_to user
Syntax error! `:` is missing
belongs_to :user

2019-02-26 10:24 UTC, hawkprovvv commented on app/models/post.rb
> +  belongs_to user
fixed

2019-02-26 10:25 UTC, hawkprovvv commented on config/environments/development.rb
> +  #config.action_mailer.default_url_options = { :host => 'localhost:3000' }
fixed

2019-02-26 10:26 UTC, hawkprovvv commented on test/fixtures/admin_users.yml
> +# Read about fixtures at http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
fixed

2019-02-26 10:27 UTC, hawkprovvv commented on test/models/admin_user_test.rb
> +require 'test_helper'
fixed

2019-02-26 10:40 UTC, hawkprovvv commented on config/locales/devise.en.yml
> +# Additional translations at https://github.com/plataformatec/devise/wiki/I18n
fixed

2019-03-05 18:14 UTC, slenderock requested changes
remove DS_Store files from index

2019-03-05 18:14 UTC, slenderock commented on app/models/follower_user.rb
> +  belongs_to :follower, foreign_key: { to_table: :users }
class_name: 'User'

2019-03-05 18:14 UTC, slenderock commented on app/models/follower_user.rb
> +  belongs_to :follower, foreign_key: { to_table: :users }
foreign_key: { to_table: :users }
doesn't works in models

2019-03-05 18:14 UTC, slenderock commented on app/models/role.rb
> +  enumerize :name, in: [:admin, :member], default: :member
change to -> `%i[admin member]`

2019-03-05 19:02 UTC, slenderock approved these changes

2019-03-05 19:02 UTC, merged